### ISSUE TITLE
MaaS360 support

### ISSUE THREAD

**Issue by brunes007** [devadvance/rootcloak#109] opened 2016-08-24 22:20 UTC
Please fix whatever issue is preventing Rootcloak from working with MaaS360.  My own analysis shows it is simply a matter of how they are looking for the binary.  I am willing to do a bug bounty of up to $100 to get this fixed for once and for all.

**Comment by hikaritenchi** [comment] 2016-10-06 18:52
Closed as duplicate of #23

**Closed as completed by hikaritenchi** 2016-10-06 18:52 UTC
