### ISSUE TITLE
eToken

### ISSUE THREAD

**Issue by bl00dreaver** [devadvance/rootcloak#94] opened 2016-07-28 11:17 UTC
Hi,
eToken (Banking App) does not work with any version (stable or 3.0)
Could you check if you can fix it?
https://www.dropbox.com/s/dc2zu84u72rpg7d/eToken_com.eTokenBCR.apk?dl=0

**Comment by andreiiliuta** [comment] 2016-07-28 14:38
this is already opened #86

**Comment by hikaritenchi** [comment] 2016-07-28 17:49
Closed as duplicate of #86

**Closed by hikaritenchi** 2016-07-28 17:49 UTC
